language: java
jdk:
    - oraclejdk8
    - oraclejdk7
cache:
    directories:
        - $HOME/.m2/
script:
    - mvn test
after_success:
    - mvn cobertura:cobertura -Dcobertura.report.format=xml coveralls:report -DrepoToken=$COVERALL_TOKEN
